/**
 * LES MOTS ESPAGNOLS ET PORTUGAIS DES RAISONS SOCIALES : ce que le dictionnaire anglais ne sait pas dire.
 *
 * « Ferretería El Faro » et « Ferretería El Foro », « Comercial Manzana Verde » et « Comercial Manzano
 * Verde », « Transportes Refrigerados del Sureste » et « … del Suroeste » sont deux commerces chacun :
 * le phare et le forum, le pommier et la pomme, le sud-est et le sud-ouest. Le dictionnaire anglais
 * connaît « faro » (un jeu de cartes) et « manzana » (entré au Webster par l'Amérique espagnole) mais
 * pas leurs voisins, et deux mots dont un seul est anglais passaient pour une faute de frappe ou le
 * correcteur d'un téléphone (jeu 11, 27/09 : trois fausses alertes fortes, 0,903, 0,920, 0,904).
 *
 * Ce fichier est un VOCABULAIRE CHOISI, pas une liste descendue : les mots que les registres
 * d'Amérique latine, d'Espagne et du Portugal mettent dans un nom de société ou de navire. Les points
 * cardinaux, les lieux et la nature, les couleurs et les métaux, les saints et les qualificatifs, les
 * denrées et les marchandises, les métiers et les enseignes, les activités des registres, la famille
 * et les personnes morales. Écrits comme la normalisation les laisse : minuscules, sans accent, ñ en n,
 * ç en c. Deux mots de cette table sont deux mots (voir `motsHispaniquesDistincts` dans mots.ts), au
 * pluriel près ; un mot qui n'y est pas ne dit rien de lui.
 *
 * Pas de noms de famille (Muñoz, Muniz ; Gómez, Gámez) : le plafond du mot court ambigu les range déjà
 * au possible, et une liste de patronymes ne serait jamais complète.
 */
export const MOTS_HISPANIQUES: ReadonlySet<string> = new Set([
  /* les points cardinaux et les régions */
  "norte", "sur", "este", "oeste", "sureste", "suroeste", "noreste", "noroeste", "sudeste", "sudoeste", "nordeste",
  "oriente", "occidente", "oriental", "occidental", "centro", "central", "austral", "boreal", "andino", "andina",
  "caribe", "pacifico", "atlantico", "mediterraneo", "cantabrico", "amazonas", "amazonico", "amazonica", "patagonia",
  "patagonico", "pampa", "pampeano", "altiplano", "litoral", "interior", "peninsular", "insular", "tropical", "tropico",
  "ecuatorial", "leste", "meridional", "septentrional",
  /* les lieux et la nature */
  "puerto", "puerta", "playa", "praia", "costa", "valle", "vale", "sierra", "serra", "golfo", "bahia", "baia", "isla",
  "islas", "ilha", "ilhas", "rio", "monte", "montana", "mar", "mares", "sol", "luna", "estrella", "estrela", "perla",
  "perola", "flor", "flores", "lago", "laguna", "lagoa", "cerro", "cabo", "punta", "ponta", "cumbre", "llano", "llanos",
  "selva", "bosque", "floresta", "mata", "campo", "prado", "huerta", "huerto", "vega", "ribera", "ribeira", "arroyo",
  "fuente", "fonte", "pozo", "poco", "cueva", "roca", "piedra", "pedra", "arena", "areia", "tierra", "terra", "cielo",
  "ceu", "viento", "vento", "nube", "lluvia", "chuva", "nieve", "neve", "fuego", "fogo", "agua", "aguas", "aire", "luz",
  "sombra", "aurora", "alba", "amanecer", "horizonte", "faro", "farol", "foro", "muelle", "puente", "ponte", "torre",
  "castillo", "castelo", "palacio", "plaza", "praca", "camino", "caminho", "calle", "avenida", "ciudad", "cidade",
  "pueblo", "povo", "villa", "aldea", "aldeia", "barrio", "bairro", "colonia", "hacienda", "fazenda", "finca", "rancho",
  "granja", "estancia", "chacra", "quinta", "molino", "moinho", "jardin", "jardim", "parque", "paseo", "rambla", "salinas",
  "mina", "minas", "cantera", "volcan", "cordillera", "peninsula", "cayo", "arrecife", "coral", "corales", "manglar",
  "estero", "marisma", "delta", "cuenca", "meseta", "paramo", "sabana", "desierto", "oasis", "canal", "presa", "embalse",
  "represa", "dique", "ensenada", "enseada", "caleta", "rada", "fondeadero", "escollera", "malecon", "morro", "cachoeira",
  "sitio", "engenho", "foz", "istmo", "archipielago", "arquipelago", "cordoba", "cruz", "cruces", "esperanza",
  "esperanca", "victoria", "vitoria", "libertad", "liberdade", "paz", "gloria", "fortuna", "progreso", "progresso",
  "porvenir", "concordia", "armonia", "harmonia", "amistad", "amizade", "alianza", "alianca", "corazon", "coracao",
  "milagro", "milagre", "tesoro", "tesouro", "joya", "joia", "diamante", "esmeralda", "rubi", "zafiro", "ambar",
  /* les couleurs et les métaux */
  "verde", "azul", "blanco", "blanca", "branco", "branca", "negro", "negra", "preto", "preta", "rojo", "roja",
  "vermelho", "vermelha", "amarillo", "amarilla", "amarelo", "amarela", "gris", "cinza", "dorado", "dorada", "dourado",
  "dourada", "plateado", "plateada", "prateado", "oro", "ouro", "plata", "prata", "bronce", "bronze", "cobre", "hierro",
  "ferro", "acero", "aco", "marfil", "marfim", "rosa", "violeta", "morado", "roxo", "naranja", "laranja", "pardo",
  /* les saints et les qualificatifs */
  "santo", "santa", "san", "sao", "nuevo", "nueva", "novo", "nova", "gran", "grande", "viejo", "vieja", "velho", "velha",
  "alto", "alta", "bajo", "baja", "baixo", "baixa", "bueno", "buena", "bello", "bella", "belo", "bela", "hermoso",
  "hermosa", "lindo", "linda", "real", "dulce", "doce", "claro", "clara", "fuerte", "forte", "libre", "livre", "feliz",
  "rapido", "rapida", "seguro", "segura", "mayor", "maior", "menor", "primero", "primera", "primeiro", "primeira",
  "segundo", "segunda", "tercero", "tercera", "terceiro", "terceira", "ultimo", "ultima", "unico", "unica", "nacional",
  "internacional", "universal", "general", "geral", "mundial", "global", "regional", "latino", "latina", "hispano",
  "hispana", "iberico", "iberica", "americano", "americana", "mexicano", "mexicana", "brasileiro", "brasileira",
  "argentino", "argentina", "chileno", "chilena", "peruano", "peruana", "colombiano", "colombiana", "panameno", "panamena",
  "espanol", "espanola", "portugues", "portuguesa", "cubano", "cubana", "dominicano", "dominicana", "venezolano",
  "venezolana", "ecuatoriano", "ecuatoriana", "boliviano", "boliviana", "uruguayo", "uruguaya", "paraguayo", "paraguaya",
  "moderno", "moderna", "antiguo", "antigua", "antigo", "clasico", "clasica", "popular", "familiar", "tradicional",
  "natural", "integral", "especial", "superior", "principal", "mayorista", "minorista", "atacadista", "varejista",
  "cuatro", "cinco", "seis", "siete", "sete", "ocho", "oito", "nueve", "nove", "diez", "veinte", "cien", "mil",
  /* les denrées et les marchandises */
  "manzana", "manzano", "maca", "naranjo", "limon", "limao", "limonero", "olivo", "oliva", "aceituna", "azeitona",
  "cafe", "cacao", "azucar", "acucar", "cana", "maiz", "milho", "trigo", "arroz", "frijol", "feijao", "papa", "patata",
  "batata", "uva", "vino", "vinho", "cerveza", "cerveja", "leche", "leite", "queso", "queijo", "carne", "carnes",
  "pescado", "pescados", "peixe", "peixes", "marisco", "mariscos", "camaron", "camarones", "camarao", "atun", "atum",
  "sardina", "sardinha", "aceite", "azeite", "harina", "farinha", "miel", "fruta", "frutas", "fruto", "frutos",
  "verdura", "verduras", "hortaliza", "hortalizas", "semilla", "semillas", "semente", "sementes", "grano", "granos",
  "grao", "graos", "madera", "maderas", "madeira", "madeiras", "cuero", "couro", "lana", "algodon", "algodao", "seda",
  "tela", "telas", "tejido", "tejidos", "tecido", "tecidos", "textil", "textiles", "textel", "ropa", "roupa", "calzado",
  "calcado", "zapato", "zapatos", "sapato", "sapatos", "mueble", "muebles", "movel", "moveis", "vidrio", "vidro",
  "cristal", "papel", "carton", "cartao", "plastico", "plasticos", "hule", "goma", "caucho", "borracha", "metal",
  "metales", "metais", "mineral", "minerales", "minerio", "carbon", "carvao", "petroleo", "energia", "electrica",
  "electrico", "eletrica", "eletrico", "solar", "eolica", "hidrica", "quimica", "quimico", "quimicos", "farmacia",
  "farmaceutica", "farmaceutico", "laboratorio", "laboratorios", "clinica", "hospital", "salud", "saude", "medico",
  "medica", "dental", "optica", "cemento", "cimento", "concreto", "ladrillo", "ladrillos", "tijolo", "marmol", "marmore",
  "granito", "ceramica", "azulejo", "azulejos", "pintura", "pinturas", "tinta", "tintas", "maquinaria", "maquina",
  "maquinas", "equipo", "equipos", "equipamento", "equipamentos", "herramienta", "herramientas", "ferramenta",
  "ferramentas", "repuesto", "repuestos", "refaccion", "refacciones", "autopartes", "automotriz", "automotor",
  "automotiva", "motor", "motores", "vehiculo", "vehiculos", "veiculo", "veiculos", "camion", "camiones", "caminhao",
  "auto", "autos", "carro", "carros", "moto", "motos", "bicicleta", "llanta", "llantas", "pneu", "pneus", "bateria",
  "baterias", "cable", "cables", "tubo", "tubos", "tuberia", "tuberias", "valvula", "valvulas", "bomba", "bombas",
  "envase", "envases", "embalaje", "embalagem", "empaque", "empaques", "bolsa", "bolsas", "saco", "sacos", "caja", "cajas",
  "caixa", "caixas", "tanque", "tanques", "cisterna", "contenedor", "contenedores", "pallet", "abono", "abonos",
  "fertilizante", "fertilizantes", "agroquimicos", "insumos", "forraje", "alimento", "alimentos", "alimenticia",
  "alimenticios", "bebida", "bebidas", "refresco", "refrescos", "jugo", "jugos", "suco", "sucos", "licor", "licores",
  "tabaco", "cigarro", "cigarros", "dulces", "chocolate", "chocolates", "galleta", "galletas", "helado", "helados",
  "lacteos", "lacteo", "laticinios", "carnico", "carnicos", "embutidos", "conserva", "conservas", "congelados", "enlatados",
  "molinos", "harinera", "arrocera", "azucarera", "cafetalera", "cacaotera", "bananera", "frutera", "vinicola",
  "vitivinicola", "destileria", "cerveceria", "cervejaria", "panela", "yerba", "mate", "quinua", "quinoa", "palma",
  "palmito", "coco", "cocos", "pina", "mango", "mangos", "aguacate", "abacate", "platano", "banana", "bananas", "papaya",
  "melon", "sandia", "fresa", "frutilla", "cereza", "durazno", "ciruela", "pera", "peras", "higo", "nuez", "nueces",
  "almendra", "almendras", "avellana", "castana", "cacahuate", "mani", "girasol", "soja", "soya", "sorgo", "cebada", "avena",
  "centeno", "lenteja", "garbanzo", "haba", "tomate", "cebolla", "ajo", "chile", "pimiento", "pimenta", "zanahoria",
  "lechuga", "espinaca", "calabaza", "pepino", "aji", "cilantro", "perejil", "hierba", "hierbas", "especia", "especias",
  "sal", "vinagre", "salsa", "salsas", "pan", "panes", "pasta", "pastas", "fideo", "fideos", "tortilla", "tortillas", "masa",
  "huevo", "huevos", "ovo", "ovos", "pollo", "pollos", "frango", "frangos", "res", "cerdo", "porco", "cordero", "cabra",
  "cabras", "ganado", "gado", "toro", "toros", "touro", "vaca", "vacas", "caballo", "caballos", "cavalo", "aguila",
  "aguia", "condor", "leon", "leao", "tigre", "lobo", "zorro", "puma", "jaguar", "delfin", "golfinho", "ballena", "baleia",
  "tiburon", "tubarao", "gaviota", "gaivota", "halcon", "paloma", "pomba", "garza", "garca", "pelicano", "colibri",
  "quetzal", "tucan", "loro", "cisne", "pato", "ganso", "abeja", "abelha", "mariposa", "borboleta", "tortuga", "tartaruga",
  "cangrejo", "langosta", "lagosta", "pulpo", "polvo", "calamar", "lula", "ostra", "ostras", "mejillon", "almeja", "concha",
  "conchas", "sirena", "sereia", "triton", "neptuno", "poseidon", "marinero", "marinheiro", "capitan", "capitao", "piloto",
  "pescador", "pescadores", "armador", "armadores", "navegante", "navegantes", "corsario", "pirata", "vikingo", "guerrero",
  "guerreiro", "principe", "princesa", "reina", "rainha", "rey", "rei", "emperador", "senor", "senora", "senhor", "senhora",
  "dona", "caballero", "cavaleiro", "dama", "nina", "nino", "menina", "menino", "hijo", "hija", "filho", "filha", "madre",
  "padre", "mae", "pai", "abuelo", "abuela", "avo", "tio", "tia", "primo", "prima", "amigo", "amiga", "amigos", "familia",
  /* les métiers et les enseignes */
  "ferreteria", "ferretera", "ferragens", "libreria", "livraria", "papeleria", "papelaria", "joyeria", "joalheria",
  "relojeria", "perfumeria", "panaderia", "padaria", "pasteleria", "confeitaria", "reposteria", "carniceria", "acougue",
  "pescaderia", "peixaria", "marisqueria", "fruteria", "verduleria", "cerrajeria", "lavanderia", "lavandaria", "tintoreria",
  "zapateria", "sapataria", "sastreria", "alfaiataria", "peluqueria", "cabeleireiro", "cafeteria", "restaurante", "restaurant",
  "cantina", "taberna", "bar", "bodega", "bodegas", "almacen", "almacenes", "armazem", "armazens", "tienda", "tiendas",
  "loja", "lojas", "mercado", "mercados", "supermercado", "supermercados", "minimercado", "abarrotes", "abasto", "abastos",
  "mercearia", "deposito", "depositos", "taller", "talleres", "oficina", "oficinas", "fabrica", "fabricas", "usina", "planta",
  "plantas", "ingenio", "ingenios", "matadero", "frigorifico", "frigorificos", "empacadora", "procesadora",
  "envasadora", "embotelladora", "refinadora", "refineria", "refinaria", "fundidora", "fundicion", "fundicao", "ensambladora",
  "maquiladora", "textilera", "confecciones", "confeccoes", "curtiembre", "curtidora", "teneria", "aserradero", "serraria",
  "carpinteria", "marcenaria", "herreria", "serralheria", "fontaneria", "plomeria", "electricidad", "eletricidade",
  "vidrieria", "vidracaria", "imprenta", "impresora", "grafica", "graficas", "editorial", "editora", "publicidad",
  "publicidade", "hotel", "hoteles", "hoteis", "hosteleria", "hoteleria", "hotelaria", "posada", "pousada", "hostal",
  "turismo", "turistica", "turistico", "viajes", "viagens", "agencia", "agencias", "farmacias", "drogueria", "drogaria",
  "boutique", "bazar", "galeria", "galerias", "estacion", "estacao", "terminal", "aeropuerto",
  "aeroporto", "astillero", "astilleros", "estaleiro", "estaleiros", "varadero", "cais", "embarcadero",
  /* les activités des registres, que les tables traduisent ou non */
  "comercial", "comerciales", "comercio", "comercios", "comercializadora", "comercializacion", "distribuidora", "distribuidores",
  "distribucion", "distribuicao", "importadora", "exportadora", "importaciones", "exportaciones", "importacao", "exportacao",
  "industrial", "industriales", "industria", "industrias", "agricola", "agricolas", "agropecuaria", "agropecuario",
  "agroindustrial", "agroindustrias", "agroindustria", "ganadera", "ganadero", "ganaderia", "pecuaria", "avicola", "avicultura",
  "porcina", "lechera", "leiteira", "forestal", "florestal", "minera", "minero", "mineria", "mineracao", "mineradora",
  "siderurgica", "siderurgia", "metalurgica", "metalurgia", "metalmecanica", "metalicas", "metalicos", "mecanica", "mecanicos",
  "electronica", "eletronica", "electronicos", "electricos", "construccion", "construcciones", "construcao", "construcoes",
  "constructora", "construtora", "obra", "obras", "inmobiliaria", "inmobiliario", "imobiliaria", "bienes", "raices",
  "urbanizadora", "promotora", "desarrolladora", "desarrollos", "proyectos", "projetos", "ingenieria", "engenharia",
  "ingenieros", "engenheiros", "arquitectura", "arquitetura", "arquitectos", "arquitetos", "consultora", "consultores",
  "consultoria", "asesores", "asesoria", "assessoria", "contadores", "contable", "contabilidade", "juridica", "abogados",
  "advogados", "notaria", "seguros", "aseguradora", "seguradora", "financiera", "financiero", "financeira", "banco", "bancaria",
  "credito", "creditos", "inversiones", "inversora", "investimentos", "capital", "patrimonial", "participaciones",
  "participacoes", "operadora", "administradora", "gestora", "gestion", "gestao", "servicio", "servicios", "servicos",
  "mantenimiento", "manutencao", "limpieza", "limpeza", "seguridad", "seguranca", "vigilancia", "comunicaciones",
  "comunicacoes", "telecomunicaciones", "telecomunicacoes", "informatica", "sistemas", "tecnologia", "tecnologias", "tecnica",
  "tecnicos", "tecnicas", "transporte", "transportes", "transportadora", "transportadores", "logistica", "logisticas",
  "logistico", "carga", "cargas", "mudanzas", "mudancas", "flete", "fletes", "fretes", "paqueteria", "mensajeria", "correo",
  "correios", "aduana", "aduanas", "aduanal", "aduanales", "aduanera", "aduanero", "alfandega", "portuaria", "portuarios",
  "portuario", "naviera", "naviero", "navieras", "maritima", "maritimo", "maritimos", "maritimas", "fluvial", "fluviales",
  "pesquera", "pesquero", "pesqueira", "pesqueiro", "pesca", "armadora", "remolcador", "remolcadores",
  "rebocador", "rebocadores", "remolque", "remolques", "barcaza", "barcazas", "lancha", "lanchas", "buque", "buques",
  "barco", "barcos", "navio", "navios", "nave", "naves", "velero", "yate", "motonave", "embarcacion", "embarcaciones",
  "embarcacao", "embarcacoes", "salvamento", "salvataje", "dragado", "dragados", "cabotaje", "cabotagem", "navegacion",
  "navegacao", "practicaje", "estiba", "estibadores", "consignataria", "consignatarios", "agenciamiento", "afretamento",
  "fletamento", "chartering", "suministros", "suprimentos", "abastecimiento", "abastecimentos", "provisiones", "provisoes",
  "materiales", "materiais", "productos", "produtos", "producciones", "producoes", "produccion", "producao", "fabricacion",
  "fabricacao", "manufactura", "manufacturas", "manufatura", "artesania", "artesanias", "artesanato", "diseno", "desenho",
  "moda", "modas", "calzados", "calcados", "texteis", "muebleria", "decoracion", "decoracao", "iluminacion",
  "iluminacao", "refrigeracion", "refrigeracao", "refrigerados", "refrigerada", "climatizacion", "ventilacion", "energetica",
  "energeticos", "petrolera", "petroleros", "petroquimica", "gasera", "combustibles", "combustiveis", "lubricantes",
  "lubrificantes", "gasolinera", "estaciones", "reciclaje", "reciclagem", "residuos", "ambiental", "ambientales",
  "ecologica", "ecologico", "hidraulica", "hidraulico", "sanitaria", "sanitarios", "saneamiento", "saneamento",
  "educativa", "educacion", "educacao", "colegio", "escuela", "escola", "instituto", "academia", "universidad", "universidade",
  "cultural", "deportiva", "deportivo", "esportiva", "esportivo", "recreativa", "musical", "artistica", "cinematografica",
  "audiovisual", "medios", "radio", "television", "televisao", "prensa", "imprensa", "digital", "digitales", "virtual",
  /* la famille et les personnes morales */
  "hermanos", "hermanas", "irmaos", "irmas", "hijos", "hijas", "filhos", "filhas", "sucesores", "sucessores", "asociados",
  "associados", "socios", "viuda", "viuva", "herederos", "herdeiros", "compania", "companhia", "sociedad", "sociedade",
  "empresa", "empresas", "grupo", "grupos", "corporacion", "corporacao", "corporativo", "consorcio", "cooperativa",
  "asociacion", "associacao", "fundacion", "fundacao", "union", "uniao", "federacion", "federacao", "camara", "casa", "hogar", "lar", "nuestra", "nuestro", "nossa", "nosso", "virgen", "virgem", "angel", "angeles",
  "anjo", "anjos", "espiritu", "espirito", "sagrado", "sagrada", "divino", "divina", "cristo", "jesus", "maria", "jose",
  "carmen", "guadalupe", "fatima", "lourdes", "rosario", "pilar", "mercedes", "socorro", "remedios", "dolores", "asuncion",
  "concepcion", "conceicao", "trinidad", "trindade", "salvador", "redentor", "aparecida", "bonfim", "nazare", "candelaria",
  "encarnacion", "purisima", "inmaculada", "imaculada", "natividad", "natal", "pascua", "pascoa",
]);
